work_dir: ./work_dir/recognition/ntu-xsub/FP_GCN_relative

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ../Datasets/NTU/NTU-RGB-D/xsub/train_fp_data.npy
  label_path: ../Datasets/NTU/NTU-RGB-D/xsub/train_fp_label.pkl
  relative: True
test_feeder_args:
  data_path: ../Datasets/NTU/NTU-RGB-D/xsub/val_fp_data.npy
  label_path: ../Datasets/NTU/NTU-RGB-D/xsub/val_fp_label.pkl
  relative: True

# model
model: net.fp_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [10, 50]

# training
device: [0]
batch_size: 1
loss_batch_size: 64
test_batch_size: 1
num_epoch: 30




