work_dir: ./work_dir/ntu-xsub/CNN

# feeder
train_feeder_args:
  data_path: ../Datasets/NTU/NTU-RGB-D/xsub/train_data.npy
  label_path: ../Datasets/NTU/NTU-RGB-D/xsub/train_label.pkl
  img_like: True
test_feeder_args:
  data_path: ../Datasets/NTU/NTU-RGB-D/xsub/val_data.npy
  label_path: ../Datasets/NTU/NTU-RGB-D/xsub/val_label.pkl
  img_like: True

# model
model_args:
  sample_size: [36, 64]
  sample_duration: 60

#optim
weight_decay: 0.0001
base_lr: 0.001
step: [10, 50]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 30




